
#Jupyter book configuration file

title: "SI470: Machine Learning"
author: "Gavin Taylor"
logo: logo.png
copyright: "2025"

# HTML settings

html:
  favicon: logo.png
  use_repository_button: true
  use_issues_button: false
  home_page_in_navbar: true
  extra_footer: |
    <p>© 2025 United States Naval Academy — Course Materials</p>


execute:
  execute_notebooks: force
  exclude_patterns:
    - "assignments/09transfer.ipynb"
    - "assignments/10facial_recognition.ipynb"

# Sphinx Extensions and JS Dependencies
sphinx:
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

# PDF / LaTeX Export
latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

# Repo
repository:
  url: https://github.com/mrburke18/SD312-jupyterbook
  branch: main
  path_to_book: ""
